name: unit_tests

on: [push, pull_request]

#on:
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: clownmik/sdl2_builder:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          ctest --output-on-failure --extra-verbose